name: uber_driver_app
description: uber driver app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #ui
  lottie: ^2.6.0
  cupertino_icons: ^1.0.4
  image_picker: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_launcher_icons: ^0.13.1

  #state management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get: ^4.6.1

  #firebase
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6

  #map
  google_maps_flutter: ^2.1.1
  geolocator: ^10.0.0
  flutter_polyline_points: ^2.0.0

  # dependency injection
  get_it: ^7.2.0
  intl: ^0.18.1

  #rxdart
  rxdart: ^0.27.3
  modal_bottom_sheet: ^2.0.0

  #network connectivity
  connectivity_plus: ^4.0.2

  # for calling
  flutter_phone_direct_caller: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true


  assets:
    - assets/
